# Generated by Django 2.2.3 on 2019-12-20 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
            ],
            options={
                'db_table': 'teacher_info',
            },
        ),
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('teach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.teacher')),
            ],
            options={
                'db_table': 'stud_info',
            },
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contct', models.IntegerField()),
                ('students', models.ManyToManyField(to='student.stud')),
                ('teachers', models.ManyToManyField(to='student.teacher')),
            ],
            options={
                'db_table': 'college_info',
            },
        ),
    ]
